version: "3.7"

services:
  wordpress:
    image: wordpress:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
      restart_policy:
        condition: on-failure
    depends_on:
      - mariadb
    ports:
      - "80:80"
    networks:
      - wordpress_private
    secrets:
      - source: mariadb_password
        target: wp_db_password
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wp_db_password
      WORDPRESS_DB_NAME: wordpress

  mariadb:
    image: mariadb:latest
    networks:
      - wordpress_private
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    secrets:
      - source: mariadb_root_password
      - source: mariadb_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mariadb_password
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress

volumes:
  mariadb_data:
  wp_data:

secrets:
  mariadb_root_password:
    file: db_root_password.txt
    name: mariadb_root_password
  mariadb_password:
    file: db_password.txt
    name: mariadb_password

networks:
  wordpress_private:
    name: wordpress_private
